//! App Fair — a small F-Droid-style app store built with [Day](https://daybrite.dev). It syncs
//! F-Droid-compatible Index V2 catalogs into on-device SQLite, lets you browse, search, and switch
//! between catalogs, and downloads/installs/updates/launches Android APKs.
//!
//! `root()` is a three-tab shell (Catalogs, Updates, Settings). Catalogs and Updates are each a
//! navigation stack that pushes an app detail page; an install overlay floats above everything.

use day::prelude::*;

mod cache;
mod catalogs_add;
mod db;
mod detail;
mod fdroid;
mod icons;
mod install;
mod install_sheet;
mod mock;
mod model;
mod net;
mod platform;
mod schema;
mod settings;
mod state;
mod sync;
mod ui;
mod updates;
mod util;

/// Typed constants for bundled resources (generated by `day-build` from `resource/`).
pub mod res {
    include!(concat!(env!("OUT_DIR"), "/day_resources.rs"));
}

day::routes! {
    /// The three top-level tabs.
    pub(crate) enum Tab {
        Catalogs => "catalogs",
        Updates => "updates",
        Settings => "settings",
    }
}

/// Destinations pushed onto a tab's navigation stack.
#[derive(Clone, PartialEq, Eq, Debug)]
pub(crate) enum Nav {
    /// An app detail page (repo id + package id encode into the route key).
    App { repo_id: i64, pkg: String },
    /// The "add a catalog" form.
    AddCatalog,
}

impl Route for Nav {
    fn key(&self) -> String {
        match self {
            Nav::App { repo_id, pkg } => format!("app-{repo_id}~{pkg}"),
            Nav::AddCatalog => "add-catalog".to_string(),
        }
    }
    fn from_key(key: &str) -> Option<Self> {
        if key == "add-catalog" {
            return Some(Nav::AddCatalog);
        }
        let rest = key.strip_prefix("app-")?;
        let (rid, pkg) = rest.split_once('~')?;
        Some(Nav::App {
            repo_id: rid.parse().ok()?,
            pkg: pkg.to_string(),
        })
    }
    /// The native nav-bar title: the app's name (from the catalog), not the wire key.
    fn title(&self) -> String {
        match self {
            Nav::App { repo_id, pkg } => {
                state::with_db(|c| db::app_name(c, *repo_id, pkg)).unwrap_or_else(|| pkg.clone())
            }
            Nav::AddCatalog => res::str::nav_add_catalog().format(),
        }
    }
}

/// Build the destination page for a pushed [`Nav`].
pub(crate) fn nav_destination(n: &Nav) -> AnyPiece {
    match n {
        Nav::App { repo_id, pkg } => detail::detail_page(*repo_id, pkg.clone()),
        Nav::AddCatalog => catalogs_add::add_catalog_page(),
    }
}

/// Push a destination onto a stack path.
pub(crate) fn push_nav(path: Signal<Vec<Nav>>, dest: Nav) {
    let mut v = path.get_untracked();
    v.push(dest);
    path.set(v);
}

pub fn root() -> AnyPiece {
    // Register UI locales (English + French) before building any piece, then follow the device
    // language (#16). Only these two ship, so anything else stays on the English default.
    install_locales(
        "en",
        &[
            ("en", include_str!("../resource/locales/en/app.ftl")),
            ("fr", include_str!("../resource/locales/fr/app.ftl")),
        ],
    );
    if platform::device_locale().to_lowercase().starts_with("fr") {
        set_locale("fr");
    }

    // Resolve the data directory on the UI thread (JNI FindClass for app classes only works
    // here) so the background sync/icon threads read the cached path.
    let _ = platform::data_dir();
    // Cache the device locale + SDK + ABIs on the UI thread (all go through the app-class bridge, so
    // they must be resolved here) so the sync threads read them without JNI. The locale drives a
    // cache re-import on change (sync::run); the SDK/ABIs pick the compatible version at sync time.
    let _ = platform::device_locale();
    let _ = platform::device_sdk();
    let _ = platform::device_abis();
    // Delete any staged APK left by a previous session (interrupted download or an install whose
    // result never arrived). Safe now — no install is in flight. Runs off-thread; `data_dir` is
    // already cached above, so it needs no JNI.
    std::thread::spawn(install::prune_stale_apks);
    if mock::enabled() {
        // Offline, deterministic mode (local testing + CI screenshots): seed the bundled catalog
        // instead of syncing from the network, and skip background update checks.
        day_reactive::on_main(mock::seed);
    } else {
        // Check every enabled catalog for updates after first paint.
        day_reactive::on_main(sync::sync_all_enabled);
        // Register the daily background update check (idempotent; keeps any existing schedule) (#7).
        platform::schedule_update_checks();
    }

    let tab = Signal::new(Tab::Catalogs);
    let catalog_path = Signal::new(Vec::<Nav>::new());
    let updates_path = Signal::new(Vec::<Nav>::new());

    let tabs = selector(tab)
        .style(SelectorStyle::Tabs)
        .item_icon(
            Tab::Catalogs,
            res::str::tab_catalogs(),
            res::images::tab_catalogs,
            move || {
                stack(catalog_path, ui::catalogs_page(catalog_path))
                    .title(res::str::app_title())
                    .destination(nav_destination)
            },
        )
        .item_icon(
            Tab::Updates,
            res::str::tab_updates(),
            res::images::tab_updates,
            move || {
                stack(updates_path, updates::updates_page(updates_path))
                    .title(res::str::nav_updates())
                    .destination(nav_destination)
            },
        )
        .item_icon(
            Tab::Settings,
            res::str::tab_settings(),
            res::images::tab_settings,
            settings::settings_page,
        )
        .id("tabs");

    // The install overlay floats above everything whenever an install is in progress.
    let install = state::install_signal();
    zstack((
        tabs.any(),
        when(
            move || install.get().is_some(),
            install_sheet::install_sheet,
        ),
    ))
    .any()
}

// Mobile entry points — each macro expands to nothing off its own platform.
day::ios_main!("App Fair", root);
day::android_main!(root);
